### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by bensku**
Add the license we've reviewed internally to this repository.

@Valtakausi/dev If you approve of the license, please:

1. Approve this pull request AND
2. Leave a comment stating that you make your prior and future contributions to **this** repository available under the license

If you still have questions and/or objections, please send me a message or comment on this PR. Don't approve unless you actually *do* approve :)

### CODE REVIEW

**Review by Laetta — APPROVED** [review]
I make my prior and future contributions to this repository available under this license

**Review by PetePetelius — APPROVED** [review]
I make my prior and future contributions to this repository available under this license

**Review by Jjergon — APPROVED** [review]
I make my prior and future contributions to this repository available under this license

**Comment by bensku** [comment]
To avoid any doubts in future: I, too, make my prior and future contributions to this repository available under the LICENSE.md in this pull request.

**Pull request merged**
